version: '3.5'

services:

  postgres:
    container_name: postgres_main_db
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: bot_main
    ports:
    - "5432:5432"

rabbitmq:
  image: rabbitmq
  command: rabbitmq-server
  expose:
  - "5672"
  - "15672"