version: '3.5'

services:

  postgres:
    container_name: postgres_main_db
    image: postgres:10.13-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: smart
    ports:
    - "5432:5432"

  rabbitmq:
    image: rabbitmq:management
    restart: always
    hostname: smart-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
    - 5672:5672
    - 15672:15672

  smart:
    image: smart:0.0.1-SNAPSHOT
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - rabbitmq